stolostron/governance-policy-status-sync

cmd/manager/main.go

Rename lease name

---

cmd/manager/main.go

https://github.com/open-cluster-management/backlog/issues/11845

revert lease name back to policy-controller

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
OWNERS
README.md
SECURITY.md

Refs:
- https://github.com/open-cluster-management/backlog/issues/12541
Signed-off-by: Justin Kulikauskas <justin.kulikauskas@gmail.com>

Use community templates

---

README.md

Rebuild this image to address scan issue https://github.com/open-cluster-management/backlog/issues/13276
Signed-off-by: Gus Parvin <gparvin@redhat.com>

rebuild image to resolve glib2 issue

---

README.md

Signed-off-by: Will Kutler <wkutler@redhat.com>
for https://github.com/open-cluster-management/backlog/issues/15241

update readme to trigger rebuild

---

pkg/controller/sync/policy_status_sync.go

Signed-off-by: Gus Parvin <gparvin@redhat.com>
Working on issue https://github.com/open-cluster-management/backlog/issues/14615
The compare didn't have the compliance state in the new status so always failed.

added the compliance state to the status compare

---

main.go
test/e2e/case5_error_handling_test.go
tool/options.go
tools.go

Signed-off-by: Will Kutler <wkutler@redhat.com>
open-cluster-management/backlog#17663

Allow using the legacy leader election method

---

controllers/sync/policy_status_sync.go

Policy status update will be skipped for hub if the status is not
changed on the managed cluster. This won't work when a cluster
is resumed from hibernation where the status on managed cluster
is not changed however the status on hub was updated due to
hibernation.
For https://github.com/open-cluster-management/backlog/issues/17867

Always compare and sync status on hub

---

controllers/sync/policy_status_sync.go

Use the correct context from PolicyReconciler

Use the correct context

---

pkg/controller/sync/policy_status_sync.go

Policy status update will be skipped for hub if the status is not
changed on the managed cluster. This won't work when a cluster
is resumed from hibernation where the status on managed cluster
is not changed however the status on hub was updated due to
hibernation.
For https://github.com/open-cluster-management/backlog/issues/17867

[release 2.4] Always compare and sync status on hub

---

.github/workflows/kind.yml
Makefile
build/common/Makefile.common.mk
build/common/config/.golangci.yml
controllers/sync/eventMapper.go
controllers/sync/eventPredicate.go
controllers/sync/policy_status_sync.go
main.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go
tool/operator-sdk-port.go
tool/options.go
version/version.go

Signed-off-by: Chunxi Luo chuluo@redhat.com
https://github.com/open-cluster-management/backlog/issues/18035

Enforce Go linting policy status sync

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
Makefile
PROJECT
README.md
SECURITY.md
build/Dockerfile
build/common/Makefile.common.mk
build/common/config/.golangci.yml
controllers/sync/eventPredicate.go
controllers/sync/policy_status_sync.go
deploy/manager/manager.yaml
deploy/operator.yaml
go.mod
go.sum
main.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go

- https://github.com/stolostron/backlog/issues/18774

Organization rename to `stolostron`

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
Makefile
README.md
SECURITY.md
build/Dockerfile
build/common/Makefile.common.mk
cmd/manager/main.go
deploy/operator.yaml
go.mod
go.sum
pkg/apis/apis.go
pkg/controller/add_status_sync.go
pkg/controller/sync/eventPredicate.go
pkg/controller/sync/policy_status_sync.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go

https://github.com/stolostron/backlog/issues/18774

[release-2.4] Rename to `stolostron`

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
Makefile
README.md
SECURITY.md
build/Dockerfile
build/common/Makefile.common.mk
cmd/manager/main.go
deploy/operator.yaml
go.mod
go.sum
pkg/apis/apis.go
pkg/controller/add_status_sync.go
pkg/controller/sync/eventPredicate.go
pkg/controller/sync/policy_status_sync.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go

[release-2.3] Rename to `stolostron`

---

main.go

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

Fix lease creation

---

cmd/manager/main.go
go.mod

https://github.com/stolostron/backlog/issues/19858
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

[release-2.4] fix lease creation

---

.github/workflows/kind.yml
.gitignore
Makefile
build/common/config/.golangci.yml
build/common/scripts/coverage_calc.sh
go.mod
go.sum
main_test.go
sonar-project.properties
test/e2e/case0_clusterns_label_test.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go

Addresses:
- https://github.com/stolostron/backlog/issues/10735
Dependency on:
- https://github.com/openshift/release/pull/26156

Add SonarCloud to GitHub Actions

---

controllers/sync/policy_status_sync.go
main.go
test/e2e/e2e_suite_test.go
tool/options.go

https://github.com/stolostron/backlog/issues/18027

Improve logging

---

.github/workflows/kind.yml
main.go

Should fix some of the framework's current problems.

Fix deploy

---

README.md

Scans detected an installed package that needs to be updated.
Refs:
- https://github.com/stolostron/backlog/issues/22079
Signed-off-by: Gus Parvin <gparvin@redhat.com>

Just running a new build to pickup latest images

---

.github/workflows/framework-kind.yml
Makefile

This will just run the e2e/kind tests from the policy framework repo -
performing some basic validation that all the policy components will
still work well together with any changes here.
Refs:
- stolostron/backlog#21795
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

Add Action to run Policy Framework tests on PRs

---

.github/workflows/kind.yml
Makefile
controllers/sync/policy_status_sync.go
main.go
main_test.go
test/e2e/case1_mutation_recovery_test.go
test/e2e/case2_status_sync_test.go
test/e2e/case3_multiple_templates_test.go
test/e2e/case4_status_merge_test.go
test/e2e/case6_event_msg_test.go
test/e2e/e2e_suite_test.go
tool/options.go

Syncing the following PRs:
* open-cluster-management-io/governance-policy-status-sync#30
The first commit is to sync the Makefile from upstream so that further merge conflicts in the Makefile don't happen.
Closes #127

Sync from open-cluster-management-io/governance-policy-status-sync: #30

---

.github/workflows/framework-kind.yml
.github/workflows/kind.yml
.github/workflows/upstream.yml

Relates:
https://github.com/stolostron/backlog/issues/24763

Use the go.mod file for the Go version in CI

---

.ci-operator.yaml
build/Dockerfile

- https://github.com/stolostron/backlog/issues/24860

Add in-repo Prow config

---

.ci-operator.yaml
build/Dockerfile
go.mod
tool/operator-sdk-port.go

- https://github.com/stolostron/backlog/issues/26063
Signed-off-by: Chunxi Luo chuluo@redhat.com
(cherry picked from commit 7195d540c6539edb58d693936168fe58c1d73ca8)
Closes #153

update go to latest version
